import React, { useMemo, useState } from "react";

const PROVINCES = [
  {
    name: "Bagmati",
    projects: 312,
    budget: "NPR 14.8B",
    progress: 72,
    delayed: 31
  },
  {
    name: "Gandaki",
    projects: 186,
    budget: "NPR 7.6B",
    progress: 68,
    delayed: 18
  },
  {
    name: "Koshi",
    projects: 201,
    budget: "NPR 6.9B",
    progress: 64,
    delayed: 22
  },
  {
    name: "Lumbini",
    projects: 174,
    budget: "NPR 6.2B",
    progress: 71,
    delayed: 19
  },
  {
    name: "Madhesh",
    projects: 143,
    budget: "NPR 5.4B",
    progress: 55,
    delayed: 27
  },
  {
    name: "Karnali",
    projects: 131,
    budget: "NPR 4.1B",
    progress: 49,
    delayed: 21
  },
  {
    name: "Sudurpashchim",
    projects: 137,
    budget: "NPR 3.2B",
    progress: 58,
    delayed: 13
  }
];

const PROJECT_STATUS = [
  { label: "Active", value: 742 },
  { label: "Completed", value: 391 },
  { label: "Delayed", value: 151 },
  { label: "Critical", value: 37 }
];

const MONTHLY_PROGRESS = [
  { month: "Apr", value: 54 },
  { month: "May", value: 58 },
  { month: "Jun", value: 61 },
  { month: "Jul", value: 63 },
  { month: "Aug", value: 65 },
  { month: "Sep", value: 67 }
];

function Reports() {
  const [province, setProvince] = useState("All");
  const [period, setPeriod] = useState("2026");

  const filteredProvinces = useMemo(function () {
    if (province === "All") {
      return PROVINCES;
    }

    return PROVINCES.filter(function (item) {
      return item.name === province;
    });
  }, [province]);

  const totalProjects = 1284;
  const totalBudget = "NPR 48.2B";
  const allocated = "NPR 34.7B";
  const remaining = "NPR 13.5B";
  const overallProgress = 67;
  const delayedProjects = 151;
  const criticalProjects = 37;
  const aiFlags = 23;
  const complaints = 184;

  function exportReport() {
    const reportData = [
      "PROJECTWATCH NEPAL — PROJECT REPORT",
      "",
      "Reporting Period: " + period,
      "Province: " + province,
      "",
      "Total Projects: " + totalProjects,
      "Total Budget: " + totalBudget,
      "Allocated Budget: " + allocated,
      "Remaining Budget: " + remaining,
      "Overall Progress: " + overallProgress + "%",
      "Delayed Projects: " + delayedProjects,
      "Critical Projects: " + criticalProjects,
      "AI Flags: " + aiFlags,
      "Citizen Complaints: " + complaints,
      "",
      "Generated by ProjectWatch Nepal"
    ].join("\n");

    const blob = new Blob([reportData], {
      type: "text/plain;charset=utf-8"
    });

    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");

    link.href = url;
    link.download = "projectwatch-nepal-report-" + period + ".txt";

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  }

  return React.createElement(
    "main",
    { className: "reports-page" },

    /* HEADER */

    React.createElement(
      "div",
      { className: "reports-page-header" },

      React.createElement(
        "div",
        null,

        React.createElement(
          "div",
          { className: "breadcrumb" },
          "ProjectWatch Nepal",
          React.createElement("span", null, "/"),
          " Reports"
        ),

        React.createElement("h1", null, "Project Reports"),

        React.createElement(
          "p",
          null,
          "Government project performance, budget and risk analytics."
        )
      ),

      React.createElement(
        "button",
        {
          className: "reports-export-button",
          onClick: exportReport
        },
        "↓ Export Report"
      )
    ),

    /* FILTERS */

    React.createElement(
      "section",
      { className: "reports-filter-card" },

      React.createElement(
        "div",
        { className: "reports-filter-title" },

        React.createElement(
          "span",
          null,
          "📊"
        ),

        React.createElement(
          "div",
          null,
          React.createElement("strong", null, "Report Filters"),
          React.createElement(
            "small",
            null,
            "Select reporting period and province"
          )
        )
      ),

      React.createElement(
        "div",
        { className: "reports-filter-controls" },

        React.createElement(
          "div",
          { className: "reports-filter-field" },

          React.createElement("label", null, "REPORTING PERIOD"),

          React.createElement(
            "select",
            {
              value: period,
              onChange: function (e) {
                setPeriod(e.target.value);
              }
            },

            React.createElement(
              "option",
              { value: "2026" },
              "Fiscal Year 2026"
            ),

            React.createElement(
              "option",
              { value: "2025" },
              "Fiscal Year 2025"
            ),

            React.createElement(
              "option",
              { value: "2024" },
              "Fiscal Year 2024"
            )
          )
        ),

        React.createElement(
          "div",
          { className: "reports-filter-field" },

          React.createElement("label", null, "PROVINCE"),

          React.createElement(
            "select",
            {
              value: province,
              onChange: function (e) {
                setProvince(e.target.value);
              }
            },

            React.createElement(
              "option",
              { value: "All" },
              "All Provinces"
            ),

            PROVINCES.map(function (item) {
              return React.createElement(
                "option",
                {
                  key: item.name,
                  value: item.name
                },
                item.name
              );
            })
          )
        )
      )
    ),

    /* MAIN KPI */

    React.createElement(
      "div",
      { className: "reports-kpi-grid" },

      React.createElement(
        "div",
        { className: "reports-kpi-card blue" },

        React.createElement(
          "span",
          { className: "reports-kpi-icon" },
          "📁"
        ),

        React.createElement(
          "div",
          null,
          React.createElement("small", null, "TOTAL PROJECTS"),
          React.createElement("strong", null, totalProjects),
          React.createElement(
            "p",
            null,
            "+8.4% from previous period"
          )
        )
      ),

      React.createElement(
        "div",
        { className: "reports-kpi-card green" },

        React.createElement(
          "span",
          { className: "reports-kpi-icon" },
          "💰"
        ),

        React.createElement(
          "div",
          null,
          React.createElement("small", null, "TOTAL BUDGET"),
          React.createElement("strong", null, totalBudget),
          React.createElement(
            "p",
            null,
            allocated + " allocated"
          )
        )
      ),

      React.createElement(
        "div",
        { className: "reports-kpi-card purple" },

        React.createElement(
          "span",
          { className: "reports-kpi-icon" },
          "📈"
        ),

        React.createElement(
          "div",
          null,
          React.createElement("small", null, "OVERALL PROGRESS"),
          React.createElement("strong", null, overallProgress + "%"),
          React.createElement(
            "p",
            null,
            "+4.2% improvement"
          )
        )
      ),

      React.createElement(
        "div",
        { className: "reports-kpi-card red" },

        React.createElement(
          "span",
          { className: "reports-kpi-icon" },
          "⚠"
        ),

        React.createElement(
          "div",
          null,
          React.createElement("small", null, "CRITICAL PROJECTS"),
          React.createElement("strong", null, criticalProjects),
          React.createElement(
            "p",
            null,
            delayedProjects + " delayed projects"
          )
        )
      )
    ),

    /* CHART AREA */

    React.createElement(
      "div",
      { className: "reports-chart-grid" },

      /* PROGRESS CHART */

      React.createElement(
        "section",
        { className: "reports-chart-card progress-chart-card" },

        React.createElement(
          "div",
          { className: "reports-card-header" },

          React.createElement(
            "div",
            null,
            React.createElement("h2", null, "Project Progress"),
            React.createElement(
              "p",
              null,
              "Overall completion trend"
            )
          ),

          React.createElement(
            "span",
            { className: "reports-card-badge" },
            "67% Complete"
          )
        ),

        React.createElement(
          "div",
          { className: "reports-line-chart" },

          React.createElement(
            "div",
            { className: "reports-y-axis" },

            React.createElement("span", null, "100%"),
            React.createElement("span", null, "75%"),
            React.createElement("span", null, "50%"),
            React.createElement("span", null, "25%"),
            React.createElement("span", null, "0%")
          ),

          React.createElement(
            "div",
            { className: "reports-chart-area" },

            React.createElement(
              "div",
              { className: "reports-grid-lines" },

              React.createElement("span", null),
              React.createElement("span", null),
              React.createElement("span", null),
              React.createElement("span", null),
              React.createElement("span", null)
            ),

            React.createElement(
              "div",
              { className: "reports-progress-bars" },

              MONTHLY_PROGRESS.map(function (item) {
                return React.createElement(
                  "div",
                  {
                    key: item.month,
                    className: "reports-progress-column"
                  },

                  React.createElement(
                    "div",
                    {
                      className: "reports-progress-value",
                      style: {
                        height: item.value + "%"
                      }
                    },
                    React.createElement(
                      "span",
                      null,
                      item.value + "%"
                    )
                  ),

                  React.createElement(
                    "small",
                    null,
                    item.month
                  )
                );
              })
            )
          )
        )
      ),

      /* STATUS */

      React.createElement(
        "section",
        { className: "reports-chart-card status-chart-card" },

        React.createElement(
          "div",
          { className: "reports-card-header" },

          React.createElement(
            "div",
            null,
            React.createElement("h2", null, "Project Status"),
            React.createElement(
              "p",
              null,
              "Current project distribution"
            )
          )
        ),

        React.createElement(
          "div",
          { className: "reports-status-total" },

          React.createElement(
            "strong",
            null,
            "1,284"
          ),

          React.createElement(
            "small",
            null,
            "Total Projects"
          )
        ),

        React.createElement(
          "div",
          { className: "reports-status-list" },

          PROJECT_STATUS.map(function (item) {
            const percentage = Math.round(
              (item.value / totalProjects) * 100
            );

            return React.createElement(
              "div",
              {
                key: item.label,
                className: "reports-status-row"
              },

              React.createElement(
                "div",
                { className: "reports-status-label" },

                React.createElement(
                  "span",
                  null,
                  item.label
                ),

                React.createElement(
                  "strong",
                  null,
                  item.value
                )
              ),

              React.createElement(
                "div",
                { className: "reports-status-track" },

                React.createElement("span", {
                  className:
                    "status-" +
                    item.label.toLowerCase(),

                  style: {
                    width: percentage + "%"
                  }
                })
              )
            );
          })
        )
      )
    ),

    /* BUDGET + RISK */

    React.createElement(
      "div",
      { className: "reports-secondary-grid" },

      React.createElement(
        "section",
        { className: "reports-budget-card" },

        React.createElement(
          "div",
          { className: "reports-card-header" },

          React.createElement(
            "div",
            null,
            React.createElement("h2", null, "Budget Utilization"),
            React.createElement(
              "p",
              null,
              "Government project allocation"
            )
          )
        ),

        React.createElement(
          "div",
          { className: "reports-budget-main" },

          React.createElement(
            "div",
            { className: "reports-budget-circle" },

            React.createElement(
              "div",
              null,
              React.createElement(
                "strong",
                null,
                "72%"
              ),
              React.createElement(
                "small",
                null,
                "Allocated"
              )
            )
          ),

          React.createElement(
            "div",
            { className: "reports-budget-details" },

            React.createElement(
              "div",
              null,
              React.createElement(
                "small",
                null,
                "Total Budget"
              ),
              React.createElement(
                "strong",
                null,
                totalBudget
              )
            ),

            React.createElement(
              "div",
              null,
              React.createElement(
                "small",
                null,
                "Allocated"
              ),
              React.createElement(
                "strong",
                null,
                allocated
              )
            ),

            React.createElement(
              "div",
              null,
              React.createElement(
                "small",
                null,
                "Remaining"
              ),
              React.createElement(
                "strong",
                null,
                remaining
              )
            )
          )
        )
      ),

      React.createElement(
        "section",
        { className: "reports-risk-card" },

        React.createElement(
          "div",
          { className: "reports-card-header" },

          React.createElement(
            "div",
            null,
            React.createElement("h2", null, "Risk & Verification"),
            React.createElement(
              "p",
              null,
              "Projects requiring attention"
            )
          )
        ),

        React.createElement(
          "div",
          { className: "reports-risk-list" },

          React.createElement(
            "div",
            null,
            React.createElement(
              "span",
              null,
              "⚠"
            ),
            React.createElement(
              "div",
              null,
              React.createElement(
                "strong",
                null,
                criticalProjects
              ),
              React.createElement(
                "small",
                null,
                "Critical Projects"
              )
            )
          ),

          React.createElement(
            "div",
            null,
            React.createElement(
              "span",
              null,
              "📉"
            ),
            React.createElement(
              "div",
              null,
              React.createElement(
                "strong",
                null,
                delayedProjects
              ),
              React.createElement(
                "small",
                null,
                "Delayed Projects"
              )
            )
          ),

          React.createElement(
            "div",
            null,
            React.createElement(
              "span",
              null,
              "🤖"
            ),
            React.createElement(
              "div",
              null,
              React.createElement(
                "strong",
                null,
                aiFlags
              ),
              React.createElement(
                "small",
                null,
                "AI Verification Flags"
              )
            )
          ),

          React.createElement(
            "div",
            null,
            React.createElement(
              "span",
              null,
              "👤"
            ),
            React.createElement(
              "div",
              null,
              React.createElement(
                "strong",
                null,
                complaints
              ),
              React.createElement(
                "small",
                null,
                "Citizen Complaints"
              )
            )
          )
        )
      )
    ),

    /* PROVINCE TABLE */

    React.createElement(
      "section",
      { className: "reports-province-card" },

      React.createElement(
        "div",
        { className: "reports-card-header" },

        React.createElement(
          "div",
          null,
          React.createElement(
            "h2",
            null,
            "Province-wise Performance"
          ),
          React.createElement(
            "p",
            null,
            "Project distribution and performance by province"
          )
        )
      ),

      React.createElement(
        "div",
        { className: "reports-province-table-wrap" },

        React.createElement(
          "table",
          { className: "reports-province-table" },

          React.createElement(
            "thead",
            null,

            React.createElement(
              "tr",
              null,

              React.createElement(
                "th",
                null,
                "PROVINCE"
              ),

              React.createElement(
                "th",
                null,
                "PROJECTS"
              ),

              React.createElement(
                "th",
                null,
                "BUDGET"
              ),

              React.createElement(
                "th",
                null,
                "PROGRESS"
              ),

              React.createElement(
                "th",
                null,
                "DELAYED"
              ),

              React.createElement(
                "th",
                null,
                "PERFORMANCE"
              )
            )
          ),

          React.createElement(
            "tbody",
            null,

            filteredProvinces.map(function (item) {

              let performance = "Good";

              if (item.progress < 60) {
                performance = "Needs Attention";
              } else if (item.progress < 70) {
                performance = "Moderate";
              }

              return React.createElement(
                "tr",
                { key: item.name },

                React.createElement(
                  "td",
                  { className: "province-name-cell" },
                  React.createElement(
                    "strong",
                    null,
                    item.name
                  )
                ),

                React.createElement(
                  "td",
                  null,
                  item.projects
                ),

                React.createElement(
                  "td",
                  null,
                  item.budget
                ),

                React.createElement(
                  "td",
                  { className: "province-progress-cell" },

                  React.createElement(
                    "div",
                    null,
                    item.progress + "%"
                  ),

                  React.createElement(
                    "div",
                    { className: "province-progress-track" },

                    React.createElement("span", {
                      style: {
                        width: item.progress + "%"
                      }
                    })
                  )
                ),

                React.createElement(
                  "td",
                  null,
                  React.createElement(
                    "span",
                    { className: "province-delayed" },
                    item.delayed
                  )
                ),

                React.createElement(
                  "td",
                  null,

                  React.createElement(
                    "span",
                    {
                      className:
                        "province-performance " +
                        performance
                          .toLowerCase()
                          .replace(/\s+/g, "-")
                    },
                    performance
                  )
                )
              );
            })
          )
        )
      )
    )
  );
}

export default Reports;